# Generated by Django 4.0.3 on 2022-03-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0003_disease_deleted_district_deleted_facility_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_detail',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='family_detail',
            name='first_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family_detail',
            name='last_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
