# Generated by Django 4.0.3 on 2022-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0008_alter_patient_date_of_birth_alter_patient_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
