# Generated by Django 4.0.3 on 2022-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0009_alter_patient_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
