# Generated by Django 4.0.3 on 2022-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0010_alter_patient_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_detail',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'Daughter'), ('Son', 'Son'), ('Mother', 'Mother'), ('Father', 'Father'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Friend', 'Friend')], default='Mother', max_length=20),
            preserve_default=False,
        ),
    ]
