# Generated by Django 4.0.3 on 2022-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0011_family_detail_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_detail',
            name='gender',
            field=models.BooleanField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Non-binary')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family_detail',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family_detail',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
