# Generated by Django 4.0.3 on 2022-03-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0014_alter_disease_deleted_alter_district_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
