# Generated by Django 4.0.3 on 2022-03-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0017_alter_family_detail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_detail',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arikeapp.patient'),
        ),
    ]
