# Generated by Django 4.0.3 on 2022-03-05 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arikeapp', '0018_alter_family_detail_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(blank=True, default=False, help_text='I want to receive daily reports')),
                ('send_time', models.TimeField(default=datetime.time(12, 0), help_text='Enter time in UTC format hh:mm:ss .')),
                ('last_updated', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
